<?php

$img_plus="$urlsito/images/plus.gif";
$img_minus="$urlsito/images/minus.gif";
$img_lastlink="$urlsito/images/lastlink.gif";
$img_link="$urlsito/images/link.gif";
$img_cube="$urlsito/images/cube.gif";
$img_dim="$urlsito/images/dimension2.gif";
$img_hier="$urlsito/images/hierarchy.gif";
$img_lev="$urlsito/images/level.gif";
$img_prop="$urlsito/images/property.gif";
$img_mea="$urlsito/images/measure.gif";
$img_del="$urlsito/images/delete.png";
$img_arrdown="$urlsito/images/arrow_down.png";
$img_arrup="$urlsito/images/arrow_up.png";
$img_sortasc="$urlsito/images/sort_ascend.png";
$img_sortdesc="$urlsito/images/sort_descend.png";
$img_save="$urlsito/images/save.png";
$img_back="$urlsito/images/back.png";
$img_pdf="$urlsito/images/pdf.png";
$img_home="$urlsito/images/home.png";
$img_new="$urlsito/images/new.png";
$img_open="$urlsito/images/open.png";
$img_csv="$urlsito/images/csv.png";
$img_fb="$urlsito/images/fb.png";
$img_share="$urlsito/images/share.png";
$img_tw="$urlsito/images/twitter.png";
$img_report="$urlsito/images/report.png";
$img_email="$urlsito/images/email.png";
$img_linkedin="$urlsito/images/linkedin.png";
$img_google="$urlsito/images/google.png";
$img_weka="$urlsito/images/weka.jpg";

?>
